name: Exo4

on:
  push:
    branches: [ main ]
    paths: 
      - 'exo4/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: exo4

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Add .env file
        run: |
          cp .env.example .env

      - name: Bring up compose
        run: |
          docker compose -f compose.yml up -d

      - name: Healthcheck
        run: |
          sleep 120 # Wait for Elasticsearch to be up
          curl -f http://localhost:9200/_cluster/health || exit 1
    
      - name: Shut down compose
        run: |
          docker compose -f compose.yml down